---
- name: make grafana dir
  file: path={{ grafana.root_path }} state=directory owner={{ grafana.owner }} recurse=yes
- name: download grafana
  get_url: dest={{ grafana.root_path }}/grafana-{{ grafana.version }}.tar.gz url=http://grafanarel.s3.amazonaws.com/grafana-{{ grafana.version }}.tar.gz
- name: make version dir
  file: path={{ grafana.root_path }}/grafana-{{ grafana.version }} state=directory owner={{ grafana.owner }} recurse=yes
- name: extract grafana tarball
  unarchive: src={{ grafana.root_path}}/grafana-{{ grafana.version }}.tar.gz dest={{ grafana.root_path }} copy=false creates={{ grafana.root_path }}/grafana-{{ grafana.version }}/README.md
  notify:
    - chown grafana dir {{ grafana.root_path }}
- name: link grafana version
  file: path={{ grafana.root_path }}/dist src={{ grafana.root_path }}/grafana-{{ grafana.version }} state=link owner={{ grafana.owner }}
