---
- name: make config for nginx
  template: src=nginx.conf.j2
            dest={{ grafana.nginx_config_path }}/{{ grafana.nginx_config_name }}
            owner={{ grafana.owner }}
            mode=0644
  notify:
    - reload nginx

- name: generate htpasswd for grafana {{ grafana.root_path }}
  template: src=grafana.htpasswd.j2 dest={{ grafana.root_path }}/grafana.htpasswd owner={{ grafana.owner }}
