---
# just trigger actual build process
- name: rebuild grafana {{ grafana.root_path }}
  command: /bin/true
  notify:
    - install npm modules {{ grafana.root_path }}
    - install grunt-cli {{ grafana.root_path }}
    - update npm modules {{ grafana.root_path }}
    - grunt build {{ grafana.root_path }}
    - chown grafana dir {{ grafana.root_path }}
    - make config for grafana {{ grafana.root_path }}


- name: install npm modules {{ grafana.root_path }}
  command: chdir={{ grafana.root_path }} npm install
- name: install grunt-cli {{ grafana.root_path }}
  command: chdir={{ grafana.root_path }} npm install grunt-cli
- name: update npm modules {{ grafana.root_path }}
  command: chdir={{ grafana.root_path }} npm update
- name: grunt build {{ grafana.root_path }}
  command: chdir={{ grafana.root_path }} ./node_modules/.bin/grunt build
- name: make config for grafana {{ grafana.root_path }}
  template: src=grafana.js.j2 dest={{ grafana.root_path }}/dist/config.js owner={{ grafana.owner }}
- name: chown grafana dir {{ grafana.root_path }}
  file: path={{ grafana.root_path }} state=directory owner={{ grafana.owner }} recurse=yes
